# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "N-V-__8AABDOXwDW4TLrTiydikRCN2ym9hJI1GKGR09ZLBvY";
    path = fetchzip {
      url = "https://chromium.googlesource.com/chromium/tools/depot_tools.git/+archive/4ce8ba39a3488397a2d1494f167020f21de502f3.tar.gz";
      hash = "sha256-WTzjmLFjh1yDDEvYE7Qfx8aBxMLdATx14+Jprwh8ZgQ=";
    };
  }
  {
    name = "N-V-__8AADGOTAg2qy2JMjVSleelXVWZhf9UTIjkuioQsv9-";
    path = fetchgit {
      url = "https://github.com/google/boringssl";
      rev = "535cc391915c37912ff9b3edb0cff9b3c5c77db0";
      hash = "sha256-rSmfL4FC9QgIsQJWHwGlHuAR1ntHrK271A392FacQrs=";
    };
  }
  {
    name = "N-V-__8AAJ2cNgAgfBtAw33Bxfu1IWISDeKKSr3DAqoAysIJ";
    path = fetchzip {
      url = "https://github.com/madler/zlib/releases/download/v1.3.2/zlib-1.3.2.tar.gz";
      hash = "sha256-tKLefmGqB2HVUMILJ7Gqa0v9GH7fqv64d5S5kK1tcYU=";
    };
  }
  {
    name = "N-V-__8AAJudKgCQCuIiH6MJjAiIJHfg_tT_Ew-0vZwVkCo_";
    path = fetchzip {
      url = "https://github.com/google/brotli/archive/028fb5a23661f123017c060daa546b55cf4bde29.tar.gz";
      hash = "sha256-kl8ZHt71v17QR2bDP+ad/5uixf+GStEPLQ5ooFoC5i8=";
    };
  }
  {
    name = "N-V-__8AAL15vQCI63ZL6Zaz5hJg6JTEgYXGbLnMFSnf7FT3";
    path = fetchzip {
      url = "https://github.com/nghttp2/nghttp2/releases/download/v1.68.0/nghttp2-1.68.0.tar.gz";
      hash = "sha256-vNMN3b2tPRF0XhBlbrwZxZiLop7QDIbVWCZmEmlQb/I=";
    };
  }
  {
    name = "N-V-__8AALp9QAGn6CCHZ6fK_FfMyGtG824LSHYHHasM3w-y";
    path = fetchzip {
      url = "https://github.com/curl/curl/releases/download/curl-8_18_0/curl-8.18.0.tar.gz";
      hash = "sha256-//iOgGs/eZqciVZdgaf+PrmiFb3ACH4aTICVD4/Hkbg=";
    };
  }
  {
    name = "boringssl-0.1.0-VtJeWehMAAA4RNnwRnzEvKcS9rjsR1QVRw1uJrwXxmVK";
    path = fetchgit {
      url = "https://github.com/Syndica/boringssl-zig";
      rev = "c53df00d06b02b755ad88bbf4d1202ed9687b096";
      hash = "sha256-I6ST8fEQ35At/cRxjXJGxDiqZHhoJnW9n7GrhpO6RmE=";
    };
  }
  {
    name = "v8-0.0.0-xddH6_F3BAAiFvKY6R1H-gkuQlk19BkDQ0--uZuTrSup";
    path = fetchzip {
      url = "https://github.com/lightpanda-io/zig-v8-fork/archive/refs/tags/v0.3.4.tar.gz";
      hash = "sha256-86P24bN0n2zWBzSIdFz8rLIR8SARUtUsfHD11Psdrv0=";
    };
  }
]
