# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "N-V-__8AABDOXwDW4TLrTiydikRCN2ym9hJI1GKGR09ZLBvY";
    path = fetchzip {
      url = "https://chromium.googlesource.com/chromium/tools/depot_tools.git/+archive/4ce8ba39a3488397a2d1494f167020f21de502f3.tar.gz";
      hash = "sha256-WTzjmLFjh1yDDEvYE7Qfx8aBxMLdATx14+Jprwh8ZgQ=";
    };
  }
  {
    name = "N-V-__8AADGOTAg2qy2JMjVSleelXVWZhf9UTIjkuioQsv9-";
    path = fetchgit {
      url = "https://github.com/google/boringssl";
      rev = "535cc391915c37912ff9b3edb0cff9b3c5c77db0";
      hash = "sha256-rSmfL4FC9QgIsQJWHwGlHuAR1ntHrK271A392FacQrs=";
    };
  }
  {
    name = "N-V-__8AAJ2cNgAgfBtAw33Bxfu1IWISDeKKSr3DAqoAysIJ";
    path = fetchzip {
      url = "https://release-assets.githubusercontent.com/github-production-release-asset/2359378/2edd97fb-483d-430f-802b-a4c0ec76b851?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-27T14%3A29%3A27Z&rscd=attachment%3B+filename%3Dzlib-1.3.2.tar.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-27T13%3A28%3A44Z&ske=2026-03-27T14%3A29%3A27Z&sks=b&skv=2018-11-09&sig=jBCH5xB0M%2Bfc5QG9xjIegy769NzN0m6VrgyXa6E188Q%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3NDYxODg1MiwibmJmIjoxNzc0NjE4NTUyLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.togF6QQSAkCm8z_AGSUg4gG9iI73ym-A0esMfQUlJ9Q&response-content-disposition=attachment%3B%20filename%3Dzlib-1.3.2.tar.gz&response-content-type=application%2Foctet-stream";
      hash = "sha256-tKLefmGqB2HVUMILJ7Gqa0v9GH7fqv64d5S5kK1tcYU=";
    };
  }
  {
    name = "N-V-__8AAJudKgCQCuIiH6MJjAiIJHfg_tT_Ew-0vZwVkCo_";
    path = fetchzip {
      url = "https://codeload.github.com/google/brotli/tar.gz/028fb5a23661f123017c060daa546b55cf4bde29";
      hash = "sha256-kl8ZHt71v17QR2bDP+ad/5uixf+GStEPLQ5ooFoC5i8=";
    };
  }
  {
    name = "N-V-__8AAL15vQCI63ZL6Zaz5hJg6JTEgYXGbLnMFSnf7FT3";
    path = fetchzip {
      url = "https://release-assets.githubusercontent.com/github-production-release-asset/11452676/ffc6f61b-9235-4d0f-96e4-97661a508620?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-27T14%3A35%3A40Z&rscd=attachment%3B+filename%3Dnghttp2-1.68.0.tar.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-27T13%3A35%3A12Z&ske=2026-03-27T14%3A35%3A40Z&sks=b&skv=2018-11-09&sig=ralucBrXYX7ahBp%2Bp6adkT5X7KoJqyLqUruz18iHuLs%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3NDYxODg1MywibmJmIjoxNzc0NjE4NTUzLCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.5SmVwdiT3OWf6Bz1-nvpNUS-RIx_kAzxH1LP2ZU_gq8&response-content-disposition=attachment%3B%20filename%3Dnghttp2-1.68.0.tar.gz&response-content-type=application%2Foctet-stream";
      hash = "sha256-vNMN3b2tPRF0XhBlbrwZxZiLop7QDIbVWCZmEmlQb/I=";
    };
  }
  {
    name = "N-V-__8AALp9QAGn6CCHZ6fK_FfMyGtG824LSHYHHasM3w-y";
    path = fetchzip {
      url = "https://release-assets.githubusercontent.com/github-production-release-asset/569041/b53f91b6-5d9c-483e-86ec-216fb0b0e743?sp=r&sv=2018-11-09&sr=b&spr=https&se=2026-03-27T14%3A18%3A30Z&rscd=attachment%3B+filename%3Dcurl-8.18.0.tar.gz&rsct=application%2Foctet-stream&skoid=96c2d410-5711-43a1-aedd-ab1947aa7ab0&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skt=2026-03-27T13%3A18%3A02Z&ske=2026-03-27T14%3A18%3A30Z&sks=b&skv=2018-11-09&sig=mNmIdIYQ3uETeR3HNEtn0oPAPw6%2F4n5qJ3Ty%2Ft4u4hs%3D&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmVsZWFzZS1hc3NldHMuZ2l0aHVidXNlcmNvbnRlbnQuY29tIiwia2V5Ijoia2V5MSIsImV4cCI6MTc3NDYxODg1OSwibmJmIjoxNzc0NjE4NTU5LCJwYXRoIjoicmVsZWFzZWFzc2V0cHJvZHVjdGlvbi5ibG9iLmNvcmUud2luZG93cy5uZXQifQ.HQa5twyalKxS-6aN0XUKlsvozFbAbEQmxwD3b73EzXQ&response-content-disposition=attachment%3B%20filename%3Dcurl-8.18.0.tar.gz&response-content-type=application%2Foctet-stream";
      hash = "sha256-//iOgGs/eZqciVZdgaf+PrmiFb3ACH4aTICVD4/Hkbg=";
    };
  }
  {
    name = "boringssl-0.1.0-VtJeWehMAAA4RNnwRnzEvKcS9rjsR1QVRw1uJrwXxmVK";
    path = fetchgit {
      url = "https://github.com/Syndica/boringssl-zig";
      rev = "c53df00d06b02b755ad88bbf4d1202ed9687b096";
      hash = "sha256-I6ST8fEQ35At/cRxjXJGxDiqZHhoJnW9n7GrhpO6RmE=";
    };
  }
  {
    name = "v8-0.0.0-xddH6_F3BAAiFvKY6R1H-gkuQlk19BkDQ0--uZuTrSup";
    path = fetchzip {
      url = "https://codeload.github.com/lightpanda-io/zig-v8-fork/tar.gz/refs/tags/v0.3.4";
      hash = "sha256-86P24bN0n2zWBzSIdFz8rLIR8SARUtUsfHD11Psdrv0=";
    };
  }
]
