[package]
name = "lightpanda-ffi"
version = "0.1.0"
edition = "2021"

[lib]
name = "lightpanda_ffi"
path = "lib.rs"
crate-type = ["staticlib"]

[dependencies]
lightpanda-html5ever = { path = "../html5ever" }
lightpanda-render = { path = "../render" }
tikv-jemallocator = { version = "0.6.1", features = ["stats"], optional = true }
tikv-jemalloc-ctl = { version = "0.6.1", features = ["stats"], optional = true }

[features]
memstats = ["dep:tikv-jemallocator", "dep:tikv-jemalloc-ctl"]
