#!/usr/bin/env bash
set -o errexit #  exit on errors
set -o nounset # exit on use of uninitialized variable
set -o errtrace # inherits trap on ERR in function and subshell
source utils.sh

REVISION=13.6.233.8

cloneDep() {
  if [ -d "${2}" ]; then
    warn "dependency ${2} already exists, skipping"
  else
    say "cloning dependency ${1}"
    git clone --depth=1 "${1}" "${2}"
    pushd "${2}"
      git fetch --depth=1 origin $3
      git checkout $3
      git branch -D \@{-1}  # if you want to tidy up the fetched branch
    popd
  fi
}

if [ -d "src" ]; then
  warn "v8/src/ already exists, only cloning dependencies"
else
  say "cloning V8 into v8/src/"
  git clone --depth=1 --branch ${REVISION} "https://chromium.googlesource.com/v8/v8.git" src
fi

# TODO: we should generate this from src/DEPS
cloneDep 'https://chromium.googlesource.com/chromium/src/build.git' 'src/build' '451ef881d77fff0b7a8bbfa61934f5e4a35b4c96'
cloneDep 'https://chromium.googlesource.com/chromium/src/buildtools.git' 'src/buildtools' '6f359296daa889aa726f3d05046b9f37be241169'
cloneDep 'https://chromium.googlesource.com/chromium/src/tools/clang.git' 'src/tools/clang' '0078c27c43cae91e96bb28d8a4407045966e0542'
cloneDep 'https://chromium.googlesource.com/chromium/src/third_party/zlib.git' 'src/third_party/zlib' '788cb3c270e8700b425c7bdca1f9ce6b0c1400a9'
cloneDep 'https://chromium.googlesource.com/external/github.com/google/googletest.git' 'src/third_party/googletest/src' '52204f78f94d7512df1f0f3bea1d47437a2c3a58'
cloneDep 'https://chromium.googlesource.com/chromium/src/third_party/jinja2.git' 'src/third_party/jinja2' '9f8efc8637f847ab1ba984212598e6fb9cf1b3d4'
cloneDep 'https://chromium.googlesource.com/chromium/src/third_party/markupsafe.git' 'src/third_party/markupsafe' '9f8efc8637f847ab1ba984212598e6fb9cf1b3d4'
cloneDep 'https://chromium.googlesource.com/chromium/deps/icu.git' 'src/third_party/icu' 'c9fb4b3a6fb54aa8c20a03bbcaa0a4a985ffd34b'
cloneDep 'https://chromium.googlesource.com/chromium/src/third_party/abseil-cpp.git' 'src/third_party/abseil-cpp' '3fbb10e80d80e3430224b75add53c47c7a711612'
cloneDep 'https://chromium.googlesource.com/chromium/src/third_party/simdutf.git' 'src/third_party/simdutf' '40d1fa26cd5ca221605c974e22c001ca2fb12fde'
cloneDep 'https://chromium.googlesource.com/external/github.com/google/highway.git' 'src/third_party/highway/src/' '00fe003dac355b979f36157f9407c7c46448958e'
cloneDep 'https://chromium.googlesource.com/external/github.com/llvm/llvm-project/libcxx.git' 'src/third_party/libc++/src' '449310fe2e37834a7e62972d2a690cade2ef596b'
cloneDep 'https://chromium.googlesource.com/external/github.com/llvm/llvm-project/libcxxabi.git' 'src/third_party/libc++abi/src' '94c5d7a8edc09f0680aee57548c0b5d400c2840d'
cloneDep 'https://chromium.googlesource.com/external/github.com/llvm/llvm-project/libc.git' 'src/third_party/llvm-libc/src' '188329a7f2118a957efbb3e6219c255e7dba997c'
cloneDep 'https://chromium.googlesource.com/external/github.com/Maratyszcza/FP16.git' 'src/third_party/fp16/src' '0a92994d729ff76a58f692d3028ca1b64b145d91'
cloneDep 'https://chromium.googlesource.com/external/github.com/fastfloat/fast_float.git' 'src/third_party/fast_float/src' 'cb1d42aaa1e14b09e1452cfdef373d051b8c02a4'

# Add an empty gclient_args.gni so gn is happy. gclient also creates an empty file.
echo "# generated by get_v8.sh" >  src/build/config/gclient_args.gni

say "gettting prebuilt clang binary"
python3 src/tools/clang/scripts/update.py
