param(
    [string]$RepoRoot = "C:\Users\adyba\src\lightpanda-browser",
    [switch]$CleanBuildCaches,
    [switch]$CleanDependencyCaches,
    [switch]$CleanSliceOutputs
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Get-PathSizeBytes {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    if (-not (Test-Path -LiteralPath $Path)) {
        return [int64]0
    }

    $sum = [int64]0
    foreach ($file in (Get-ChildItem -LiteralPath $Path -Recurse -Force -File -ErrorAction SilentlyContinue)) {
        $sum += [int64]$file.Length
    }
    return $sum
}

function Get-FileSizeBytes {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    if (-not (Test-Path -LiteralPath $Path)) {
        return [int64]0
    }

    return [int64](Get-Item -LiteralPath $Path -Force).Length
}

function Format-Size {
    param(
        [Parameter(Mandatory = $true)]
        [int64]$Bytes
    )

    if ($Bytes -ge 1TB) { return "{0:N2} TB" -f ($Bytes / 1TB) }
    if ($Bytes -ge 1GB) { return "{0:N2} GB" -f ($Bytes / 1GB) }
    if ($Bytes -ge 1MB) { return "{0:N2} MB" -f ($Bytes / 1MB) }
    if ($Bytes -ge 1KB) { return "{0:N2} KB" -f ($Bytes / 1KB) }
    return "{0} B" -f $Bytes
}

function New-ArtifactRecord {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path,
        [Parameter(Mandatory = $true)]
        [string]$Category,
        [Parameter(Mandatory = $true)]
        [bool]$DefaultClean,
        [Parameter(Mandatory = $true)]
        [string]$Reason,
        [Parameter(Mandatory = $true)]
        [ValidateSet("directory", "file")]
        [string]$Kind
    )

    $exists = Test-Path -LiteralPath $Path
    $bytes = if (-not $exists) {
        [int64]0
    } elseif ($Kind -eq "file") {
        Get-FileSizeBytes -Path $Path
    } else {
        Get-PathSizeBytes -Path $Path
    }

    [pscustomobject]@{
        Path = $Path
        Name = Split-Path -Path $Path -Leaf
        Kind = $Kind
        Category = $Category
        DefaultClean = $DefaultClean
        Exists = $exists
        SizeBytes = $bytes
        Size = Format-Size -Bytes $bytes
        Reason = $Reason
    }
}

function Remove-Artifact {
    param(
        [Parameter(Mandatory = $true)]
        [pscustomobject]$Artifact
    )

    if (-not $Artifact.Exists) {
        return
    }

    if ($Artifact.Kind -eq "directory") {
        Remove-Item -LiteralPath $Artifact.Path -Recurse -Force
    } else {
        Remove-Item -LiteralPath $Artifact.Path -Force
    }
}

$artifacts = @(
    (New-ArtifactRecord -Path (Join-Path $RepoRoot ".zig-cache") -Category "Build cache" -DefaultClean $true -Reason "Transient Zig local cache. Safe to delete; next build will be cold." -Kind "directory"),
    (New-ArtifactRecord -Path (Join-Path $RepoRoot ".zig-cache-next") -Category "Build cache" -DefaultClean $true -Reason "Alternate transient Zig cache from local slice builds. Safe to delete." -Kind "directory"),
    (New-ArtifactRecord -Path (Join-Path $RepoRoot "zig-out-slice") -Category "Slice output" -DefaultClean $true -Reason "Local slice output directory. Regenerated by slice builds." -Kind "directory"),
    (New-ArtifactRecord -Path (Join-Path $RepoRoot "lightpanda-slice.exe") -Category "Slice output" -DefaultClean $true -Reason "Manual local slice binary. Safe to delete if not in use." -Kind "file"),
    (New-ArtifactRecord -Path (Join-Path $RepoRoot "lightpanda-slice.pdb") -Category "Slice output" -DefaultClean $true -Reason "Debug symbols for manual local slice binary." -Kind "file"),
    (New-ArtifactRecord -Path (Join-Path $RepoRoot "lightpanda-slice.lib") -Category "Slice output" -DefaultClean $true -Reason "Import library for manual local slice binary." -Kind "file"),
    (New-ArtifactRecord -Path (Join-Path $RepoRoot "tmp-browser-smoke\bare-metal-release") -Category "Slice output" -DefaultClean $true -Reason "Packaged bare-metal launch bundle and its smoke artifacts." -Kind "directory"),
    (New-ArtifactRecord -Path (Join-Path $RepoRoot "tmp-browser-smoke\bare-metal-release.zip") -Category "Slice output" -DefaultClean $true -Reason "Packaged bare-metal release archive." -Kind "file"),
    (New-ArtifactRecord -Path (Join-Path $RepoRoot ".lp-cache") -Category "Dependency cache" -DefaultClean $false -Reason "Bootstrap cache for downloaded tools/dependencies. Deleting is safe but costly to regenerate." -Kind "directory"),
    (New-ArtifactRecord -Path (Join-Path $RepoRoot ".lp-cache-win") -Category "Dependency cache" -DefaultClean $false -Reason "Windows V8/depot_tools cache. Large and expensive to rebuild." -Kind "directory"),
    (New-ArtifactRecord -Path (Join-Path $RepoRoot "zig-out") -Category "Primary output" -DefaultClean $false -Reason "Current compiled outputs. Usually keep unless you want a full artifact reset." -Kind "directory")
)

Write-Host "Lightpanda build artifact report"
Write-Host ""
$artifacts |
    Sort-Object @{ Expression = "SizeBytes"; Descending = $true }, Name |
    Select-Object Name,Category,Exists,DefaultClean,Size,Reason |
    Format-Table -AutoSize | Out-String -Width 220 |
    Write-Host

$toRemove = @()
if ($CleanBuildCaches) {
    $toRemove += $artifacts | Where-Object { $_.Exists -and $_.Category -eq "Build cache" }
}
if ($CleanSliceOutputs) {
    $toRemove += $artifacts | Where-Object { $_.Exists -and $_.Category -eq "Slice output" }
}
if ($CleanDependencyCaches) {
    $toRemove += $artifacts | Where-Object { $_.Exists -and $_.Category -eq "Dependency cache" }
}

$toRemove = @($toRemove | Sort-Object Path -Unique)

if ($toRemove.Count -eq 0) {
    Write-Host "No cleanup requested. Use -CleanBuildCaches, -CleanSliceOutputs, and/or -CleanDependencyCaches."
    exit 0
}

$totalBytes = ($toRemove | Measure-Object -Property SizeBytes -Sum).Sum
Write-Host ""
Write-Host ("Deleting {0} artifact(s), reclaiming about {1}." -f $toRemove.Count, (Format-Size -Bytes ([int64]$totalBytes)))

foreach ($artifact in $toRemove) {
    Write-Host ("Removing {0}" -f $artifact.Path)
    Remove-Artifact -Artifact $artifact
}

Write-Host ""
Write-Host "Cleanup complete."
